version: 2

sources:
  - name: staging
    schema: steamhub

    tables:
      - name: application_developers
        description: ""
      - name: application_genres
        description: ""
      - name: application_information
        description: ""
      - name: application_publishers
        description: ""
      - name: application_supported_languages
        description: ""
      - name: application_tags
        description: ""
      - name: player_count_history
        description: ""
      - name: price_history
        description: ""
